version: '2'
services:
  db:
    build: ./docker/development/postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/data
  app:
    build:
      context: .
      dockerfile: ./docker/development/app/Dockerfile
    command: bundle exec rails server -b '0.0.0.0' -p 3001
    stdin_open: true
    tty: true
    ports:
      - 3001:3001
    volumes: 
      - .:/app
    depends_on:
      - db
  redis:
    image: redis:4.0.11-alpine
