# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'config', '~> 1.7'
gem 'enumerize', '~> 2.2', '>= 2.2.2'
gem 'fast_jsonapi', '~> 1.3'
gem 'interactor', '~> 3.1', '>= 3.1.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rack-cors', '~> 1.0', '>= 1.0.2'
gem 'rails', '~> 5.2.0'
gem 'redis', '~> 4.0', '>= 4.0.2'
gem 'reform-rails', '~> 0.2.0.rc1'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
end

group :test do
  gem 'factory_bot_rails', '~> 4.11'
  gem 'faker', '~> 1.9', '>= 1.9.1'
  gem 'rspec-json_expectations', '~> 2.1'
  gem 'rspec-rails', '~> 3.8'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop', '~> 0.58.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
